3500 #!/usr/bin/perl -w
3501 
3502 # Generate vectors.S, the trap/interrupt entry points.
3503 # There has to be one entry point per interrupt number
3504 # since otherwise there's no way for trap() to discover
3505 # the interrupt number.
3506 
3507 print "# generated by vectors.pl - do not edit\n";
3508 print "# handlers\n";
3509 print ".globl alltraps\n";
3510 for(my $i = 0; $i < 256; $i++){
3511     print ".globl vector$i\n";
3512     print "vector$i:\n";
3513     if(!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
3514         print "  pushl \$0\n";
3515     }
3516     print "  pushl \$$i\n";
3517     print "  jmp alltraps\n";
3518 }
3519 
3520 print "\n# vector table\n";
3521 print ".data\n";
3522 print ".globl vectors\n";
3523 print "vectors:\n";
3524 for(my $i = 0; $i < 256; $i++){
3525     print "  .long vector$i\n";
3526 }
3527 
3528 # sample output:
3529 #   # handlers
3530 #   .globl alltraps
3531 #   .globl vector0
3532 #   vector0:
3533 #     pushl $0
3534 #     pushl $0
3535 #     jmp alltraps
3536 #   ...
3537 #
3538 #   # vector table
3539 #   .data
3540 #   .globl vectors
3541 #   vectors:
3542 #     .long vector0
3543 #     .long vector1
3544 #     .long vector2
3545 #   ...
3546 
3547 
3548 
3549 
